#-------------------------------
# General Site Settings
title: JingYang
logo: zz.jpeg # You can add own logo.
description: 这是我的个人主页

#-------------------------------
# Author Settings
author:
  name: Jing Yang
  image: zzz.jpeg
  say-hello: Hello, I’m <strong>杨静</strong>
  bio: 2019年毕业于西华大学建筑学专业。大学期间曾获得“大学生艺术节”设计类全国一等奖。从毕业至今就职于成都天华西南建筑有限公司。任职方案建筑师。2020年取得建筑专业技术初级职称。主要从事地产设计，参与了多个报规及投标项目。能在辅助深化户型和立面的同时加入自己的设计想法。


#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle
# wechat: yj460062420

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
